Add pagination speakers module
wnbrb/wnb-rb-site pull request #238
Opened 2024-08-06 13:42 UTC by auliafaizahr

**Title: Add Pagination to Speaker List and Adjust Layout**

**Description**
Feature Request: As an admin user, I want to manage Speakers for our Events.

**Related Problem:**
The list of speakers in speaker module is expected to grow significantly, making it difficult to maintain and navigate.

**Solution:**
This pull request adds pagination to the speaker list to improve usability. The solution utilizes the Pagy gem for pagination and Bootstrap for styling.

**Changes:**

![image](https://github.com/user-attachments/assets/04e40465-5d13-427e-a812-da5a4feca3bc)

- [x] Added pagination using pagy gem to the speaker list with 15 elements per page.
- [x] Adjusted the layout to position the pagination controls on top of the view.
- [x] Moved the "Create Speaker" button to share the same row with the title.

**Related Issues:** https://github.com/wnbrb/wnb-rb-site/issues/184

Waiting for review the changes and provide feedback from reviewer, thankyou.

2024-08-06 18:11 UTC, luciagirasoles requested changes
Congratulations for the work done here 🎉! It looks so good! we still need to improve in this PR is how we display the composition of this component in this page. Let's try to keep the same structure as it is in the Event List for Desktop and Mobile screens. (Images sent on Slack)

2024-08-07 09:11 UTC, auliafaizahr commented on Gemfile.lock
> -  x86_64-darwin-22
Restored, pls kindly check.

2024-08-18 05:38 UTC, luciagirasoles approved these changes
Thank you for the upgrades and for supporting the community.

2024-08-18 05:40 UTC, merged

2024-08-18 05:41 UTC, luciagirasoles commented
closes #238